replicaCount: 1

environment: dev
serverPort: 9000

imageName:
imageTag: latest

javaOpts: "-Xmx4000m"

global:
   hostName:

br:
   gov:
      ro:
         pge:
            sei:
               api:
                  ws:
                     url: