apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap-{{ .Release.Revision }}"
data:
  "spring.profiles.active": {{.Values.environment | quote}}
  "server.port": {{.Values.serverPort | quote}}
  "JAVA_OPTS": {{.Values.javaOpts | quote}}
  "br.gov.ro.pge.sei.api.ws.url": {{.Values.br.gov.ro.pge.sei.api.ws.url | quote }}
