apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{.Values.serverPort}}
      protocol: TCP
      targetPort: {{.Values.serverPort}}
  selector:
    app: {{ .Release.Name }}
